server:
    port: 8080
spring:
    application:
        name: MoeHub
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: moehub

        url: jdbc:mysql://b.sww.moe:33307/moehub?serverTimezone=UTC&useSSL=false
        username: 'root'
        password: '123456'
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true