server:
  port: 8080
spring:
  application:

    name: MoeHub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: moehub
    url: jdbc:mysql://b.sww.moe:33307/moehub?serverTimezone=UTC&useSSL=false
    username: 'root'
    password: '123456'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # 上传文件大小设置
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
minio:
  endpoint: http://39.103.135.63:9000
  access-key: root
  secret-key: 123456789
  bucket: moehub