server:
  port: 8080
spring:
  application:

    name: MoeHub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: moehub
    url: jdbc:mysql://10.236.29.11:3306/moehub?serverTimezone=UTC&useSSL=false
    username: root
    password: bc1f53c909b4acdc0085
  jpa:
    hibernate:
      ddl-auto: update # 自动更新数据库
    show-sql: true # 显示sql语句
  # 上传文件大小设置
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
# 显示sql绑定参数
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
minio:
  endpoint: http://10.236.29.11:9000
  access-key: minioadmin
  secret-key: 91b22b7ec6266ef1fe3d
  bucket: moehub



