// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AAvatar: typeof import("@arco-design/web-vue")["Avatar"];
    AButton: typeof import("@arco-design/web-vue")["Button"];
    AComment: typeof import("@arco-design/web-vue")["Comment"];
    AInput: typeof import("@arco-design/web-vue")["Input"];
    AInputPassword: typeof import("@arco-design/web-vue")["InputPassword"];
    ALayout: typeof import("@arco-design/web-vue")["Layout"];
    ALayoutContent: typeof import("@arco-design/web-vue")["LayoutContent"];
    ALayoutHeader: typeof import("@arco-design/web-vue")["LayoutHeader"];
    ALayoutSider: typeof import("@arco-design/web-vue")["LayoutSider"];
    AMenu: typeof import("@arco-design/web-vue")["Menu"];
    AMenuItem: typeof import("@arco-design/web-vue")["MenuItem"];
    AProgress: typeof import("@arco-design/web-vue")["Progress"];
    ARadio: typeof import("@arco-design/web-vue")["Radio"];
    ARadioGroup: typeof import("@arco-design/web-vue")["RadioGroup"];
    ATag: typeof import("@arco-design/web-vue")["Tag"];
    AUpload: typeof import("@arco-design/web-vue")["Upload"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    VideoCard: typeof import("./src/components/VideoCard.vue")["default"];
  }
}

export {};
